"""dedup de mensajes, lease de sesion y metricas de agente

Revision ID: 3c4619d0442b
Revises: ebe5d4e52cda
Create Date: 2026-08-10 18:23:30.451490
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3c4619d0442b'
down_revision: Union[str, None] = 'ebe5d4e52cda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('agent_slug', sa.String(length=30), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('tools_used', sa.String(length=300), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('tool_rounds', sa.Integer(), nullable=False),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('booked', sa.Boolean(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_agent_slug'), ['agent_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_created_at'), ['created_at'], unique=False)

    op.create_table('channel_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('worker_id', sa.String(length=64), nullable=False),
    sa.Column('lease_until', sa.DateTime(), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'channel')
    )
    with op.batch_alter_table('channel_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_sessions_company_id'), ['company_id'], unique=False)

    # 1) Columnas nuevas. El backfill va ANTES de la clave foránea: con
    # filas ya cargadas, company_id=0 no apunta a ninguna empresa y la FK
    # fallaría (lo detectó producción).
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('external_id', sa.String(length=120), nullable=True))

    # 2) Cada mensaje hereda el company_id de su conversación.
    op.execute(
        "UPDATE messages SET company_id = ("
        "SELECT company_id FROM conversations WHERE conversations.id = messages.conversation_id"
        ") WHERE company_id = 0 OR company_id IS NULL"
    )
    # Mensajes huérfanos (sin conversación): se eliminan, no se pueden atribuir.
    op.execute(
        "DELETE FROM messages WHERE conversation_id NOT IN (SELECT id FROM conversations)"
    )

    # 3) Recién ahora, índices y restricciones.
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_company_id'), ['company_id'], unique=False)
        batch_op.create_unique_constraint('uq_message_external_id', ['company_id', 'external_id'])
        batch_op.create_foreign_key('fk_messages_company', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_messages_company_id'))
        batch_op.drop_column('external_id')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('channel_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_sessions_company_id'))

    op.drop_table('channel_sessions')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_created_at'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_company_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_agent_slug'))

    op.drop_table('agent_runs')
    # ### end Alembic commands ###
