"""business packs por empresa

Revision ID: ebe5d4e52cda
Revises: 6bcb858396f3
Create Date: 2026-08-10 14:53:47.041286
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ebe5d4e52cda'
down_revision: Union[str, None] = '6bcb858396f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('packs', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('packs')

    # ### end Alembic commands ###
